// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package twitter

type Tweet struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3"
json: "message,omitempty"`
		// 참고: Protobuf는 내부 필드와 메서드도 생성하는데
		// 여기서는 생략했다.
}
